# Generated by Django 6.0.4 on 2026-04-26 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Descriptive name for the pod",
                        max_length=255,
                    ),
                ),
                ("hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("public_key", models.TextField()),
                (
                    "deadline",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("sent", "Sent")],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("encrypted_secret", models.BinaryField(blank=True, null=True)),
                (
                    "secret_type",
                    models.CharField(
                        blank=True,
                        choices=[("text", "Text"), ("file", "File")],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("encrypted_filename", models.BinaryField(blank=True, null=True)),
                ("require_sender_auth", models.BooleanField(default=False)),
                ("self_destruct", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
