name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout/releases/tag/v6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      # https://github.com/astral-sh/setup-uv/releases/tag/v8.1.0
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Install dependencies
        run: uv sync --group dev
      - name: Install Playwright browsers
        run: uv run playwright install --with-deps chromium
      - name: Start server
        run: uv run privipod --store /tmp/test.db --user admin --pass test &
      - name: Wait for server
        run: uvx wait-for-it==2.3.0 localhost:8000 --timeout 30
      - name: Run tests
        env:
          PRIVIPOD_URL: http://localhost:8000
        run: uv run pytest tests/
