name: Tests

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout/releases/tag/v6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      # https://github.com/astral-sh/setup-uv/releases/tag/v8.1.0
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Lint
        run: uvx ruff check .
      - name: Format
        run: uvx ruff format --check .
